Crown-Commercial-Service/ccs-digitalmarketplace-apiclient

.github/workflows/release.yml

Ticket: [DMPGC14-11](https://crowncommercialservice.atlassian.net/browse/DMPGC14-11)
This is the new action: https://github.com/ncipollo/release-action

DMPGC14-11 - Use maintained action to create release tags

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/audit.py

Ticket: [DMPGC14-510](https://crowncommercialservice.atlassian.net/browse/DMPGC14-510)

DMPGC14-510 - Create the conversation message audit types

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-512](https://crowncommercialservice.atlassian.net/browse/DMPGC14-512)

DMPGC14-512 - Add the api client method for the conversations

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-514](https://crowncommercialservice.atlassian.net/browse/DMPGC14-514)

DMPGC14-514 - Add the get_conversation api client method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-517](https://crowncommercialservice.atlassian.net/browse/DMPGC14-517)

DMPGC14-517 - Add the archive_conversation api client method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-516](https://crowncommercialservice.atlassian.net/browse/DMPGC14-516)

DMPGC14-516 - Add the read_conversation_message api client method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-515](https://crowncommercialservice.atlassian.net/browse/DMPGC14-515)

DMPGC14-515 - Add the create_conversation_message api client method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-513](https://crowncommercialservice.atlassian.net/browse/DMPGC14-513)

DMPGC14-513 - Add the create_conversation api client method

---

CHANGELOG.md
dmapiclient/__init__.py

Add the API client methods for the conversation messages routes

Release 25.3.0

---

dmapiclient/__init__.py
dmapiclient/data.py

Ticket: [DMPGC14-603](https://crowncommercialservice.atlassian.net/browse/DMPGC14-603)

DMPGC14-603 - Add the latest_message_target option to the API client

---

tests/test_data_api_client.py

Depends on https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-api/pull/279

Change the attachment "url" property to "file_path"

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMPGC14-610](https://crowncommercialservice.atlassian.net/browse/DMPGC14-610)

DMPGC14-610 - Add notification emails to the client

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Add subject param to the `find_communications` API client  method
[DMPGC14-615](https://crowncommercialservice.atlassian.net/browse/DMPGC14-615)

Add subject param to the `find_communications` API  client method

---

dmapiclient/data.py
tests/test_data_api_client.py

Add ability to search by message text
[DMPGC14-619](https://crowncommercialservice.atlassian.net/browse/DMPGC14-619)

add ability to search by message text

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Add ability to sort communications
[DMPGC14-620](https://crowncommercialservice.atlassian.net/browse/DMPGC14-620)

Add ability to sort communications

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-622](https://crowncommercialservice.atlassian.net/browse/DMP-622)

DMP-622 - Add the single sort by attribute to the API client

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-632](https://crowncommercialservice.atlassian.net/browse/DMP-632)
Make updates for new system message model:
- Add Audits for system messages
- Add api client methods for system messages

DMP-632 - Make updates for new system message model

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-656](https://crowncommercialservice.atlassian.net/browse/DMP-656)

DMP-656 - Add the get_supplier_evaluation method

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-658](https://crowncommercialservice.atlassian.net/browse/DMP-658)

DMP-658 - Add the update_supplier_evaluations method

---

requirements-dev.in
requirements-dev.txt

This should fix this issue: https://github.com/pypa/setuptools/issues/4483

Update the packaging version

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-664](https://crowncommercialservice.atlassian.net/browse/DMP-664)
Also update the update supplier evaluation method to a patch

DMP-664- Add the create_supplier_evaluation method

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-663](https://crowncommercialservice.atlassian.net/browse/DMP-663)

DMP-663 - Add the complete_supplier_evaluation method

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-665](https://crowncommercialservice.atlassian.net/browse/DMP-665)

DMP-665 - Add with evaluations to the find_framework_suppliers method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-668](https://crowncommercialservice.atlassian.net/browse/DMP-668)

DMP-668 - Add the get_evaluator_question method

---

dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-669](https://crowncommercialservice.atlassian.net/browse/DMP-669)

DMP-669 - Add the find_evaluator_questions method

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-673](https://crowncommercialservice.atlassian.net/browse/DMP-673)

DMP-673 - Add the update_assigned_evaluators_for_question method

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-674](https://crowncommercialservice.atlassian.net/browse/DMP-674)

DMP-674 - Add the set_final_evaluator_question method

---

dmapiclient/__init__.py
dmapiclient/data.py

Ticket: [DMP-671](https://crowncommercialservice.atlassian.net/browse/DMP-671)

DMP-671 - Add the group_evaluator_questions_by_lot_with_status method

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-684](https://crowncommercialservice.atlassian.net/browse/DMP-684)

DMP-684 - Add the find_framework_suppliers_with_evaluation_for_lot method

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket - [DMP-691](https://crowncommercialservice.atlassian.net/browse/DMP-691)

DMP-691 - Add the get_final_evaluator_question method

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-685](https://crowncommercialservice.atlassian.net/browse/DMP-685)

DMP-685 - Add find users with evaluation questions

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [DMP-1177](https://crowncommercialservice.atlassian.net/browse/DMP-1177)

DMP-1177 - Add `update_supplier_sharecode` method

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-96](https://crowncommercialservice.atlassian.net/browse/NDMP-96)

NDMP-96 - Update the create agreement method to require the signed agreement details

---

CHANGELOG.md
dmapiclient/__init__.py

Replace `setup.py` with `pyproject.toml`

Release 27.3.0

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Add routes for lot question response section evaluations
Add route for finding applicants by lot
Add param for searching by locked for some evaluation routes

Add new API routes for evaluations

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-294](https://crowncommercialservice.atlassian.net/browse/NDMP-294)

NDMP-294 - Add route for listing evaluator evaluations

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Add `with_lot_questions_response` to get evaluator evaluations
Add new method for listing lot question responses of applicants

Update some of the API methods

---

.github/dependabot.yml
CHANGELOG.md
dmapiclient/__init__.py

Update the `pyproject.toml` to add dev dependancies

Release 29.12.2

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-15](https://crowncommercialservice.atlassian.net/browse/NDMP-15)

NDMP-15 - Add `with_cdp_supplier_information` to relevant methods

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-18](https://crowncommercialservice.atlassian.net/browse/NDMP-18)

NDMP-18 - Add method for creating connection to the CDP

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-587](https://crowncommercialservice.atlassian.net/browse/NDMP-587)

NDMP-587 - Add method for revoking connection to the CDP

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-588](https://crowncommercialservice.atlassian.net/browse/NDMP-588)

NDMP-588 - Add method for updating the CDP data

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket:
- [NDMP-535](https://crowncommercialservice.atlassian.net/browse/NDMP-535)
- [NDMP-536](https://crowncommercialservice.atlassian.net/browse/NDMP-536)
- [NDMP-537](https://crowncommercialservice.atlassian.net/browse/NDMP-537)
- [NDMP-538](https://crowncommercialservice.atlassian.net/browse/NDMP-538)
- [NDMP-539](https://crowncommercialservice.atlassian.net/browse/NDMP-539)

Make major changes for communications methods

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-19](https://crowncommercialservice.atlassian.net/browse/NDMP-19)

NDMP-19 - Add route to verify the organisations

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-543](https://crowncommercialservice.atlassian.net/browse/NDMP-543)

NDMP-543 - Add api route method to get categories for framework

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/spotlight.py
tests/test_spotlight_client.py

Ticket: [NDMP-585](https://crowncommercialservice.atlassian.net/browse/NDMP-585)

NDMP-585 - Add the Spotlight API client to the other API clients

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/spotlight.py
tests/test_spotlight_client.py

Ticket: [NDMP-779](https://crowncommercialservice.atlassian.net/browse/NDMP-779)

NDMP-779 - Add the Spotlight FVRA API client to the other API clients

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Added `undo_resolve_communication` method and test.

NDMP 540 api add route to unresolve communications step 2

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-649](https://crowncommercialservice.atlassian.net/browse/NDMP-649)

NDMP-649 - Add trading name to the create CDP connection method

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/spotlight.py
tests/test_spotlight_client.py

Also, update the Spotlight FVRA API Client to be a single client which calls the different clients
Tests:

Add new Spotlight FVRA Clients for warm up call and checking multiple DUNS

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/spotlight.py
tests/test_spotlight_client.py

Pass the organisation name when sending the Spotlight warmup request

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1268](https://crowncommercialservice.atlassian.net/browse/NDMP-1268)

NDMP-1268 - Add Update Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1269](https://crowncommercialservice.atlassian.net/browse/NDMP-1269)

NDMP-1269 - Add Send Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1273](https://crowncommercialservice.atlassian.net/browse/NDMP-1273)

NDMP-1273 - Add Auth Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1267](https://crowncommercialservice.atlassian.net/browse/NDMP-1267)

NDMP-1267 - Add Get Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1270](https://crowncommercialservice.atlassian.net/browse/NDMP-1270)

NDMP-1270 - Add Approve Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1272](https://crowncommercialservice.atlassian.net/browse/NDMP-1272)

NDMP-1272 - Add Undo Send Technical Award Certificate route

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1296](https://crowncommercialservice.atlassian.net/browse/NDMP-1296)

NDMP-1296 - Rename undo tac to revert tac

---

dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1295](https://crowncommercialservice.atlassian.net/browse/NDMP-1295)

NDMP-1295 - Add route to verify if the TAC is signable

---

dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Tickets:
- [NDMP-1367](https://crowncommercialservice.atlassian.net/browse/NDMP-1367)
- [NDMP-1368](https://crowncommercialservice.atlassian.net/browse/NDMP-1368)
- [NDMP-1369](https://crowncommercialservice.atlassian.net/browse/NDMP-1369)
- [NDMP-1370](https://crowncommercialservice.atlassian.net/browse/NDMP-1370)
- [NDMP-1371](https://crowncommercialservice.atlassian.net/browse/NDMP-1371)
- [NDMP-1372](https://crowncommercialservice.atlassian.net/browse/NDMP-1372)
- [NDMP-1373](https://crowncommercialservice.atlassian.net/browse/NDMP-1373)

Add the routes for the lot pricing

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
dmapiclient/tasks.py
tests/test_data_api_client.py
tests/test_tasks_api_client.py

Ticket: [NDMP-1428](https://crowncommercialservice.atlassian.net/browse/NDMP-1428)
Add the tasks API client for the background jobs
Add endpoints for logging tasks in the audit logs

NDMP-1428 - Prepare for adding background jobs

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1428](https://crowncommercialservice.atlassian.net/browse/NDMP-1428)

NDMP-1428 - Remove endpoints for Tasks API audits

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/base.py
dmapiclient/data.py
tests/test_base_api_client.py
tests/test_data_api_client.py

Ticket: [NDMP-1506](https://crowncommercialservice.atlassian.net/browse/NDMP-1506)
Updates and enhancements to the API client:
- Major changes to the way lot question models (Evaluation, TAC and Lot Pricing) work
- Add modes to the API client to limit watch endpoints can be called

NDMP-1506 - Updates and enhancements to the API client

---

CHANGELOG.md
dmapiclient/__init__.py
dmapiclient/audit.py
dmapiclient/data.py
tests/test_data_api_client.py

Ticket: [NDMP-1497](https://crowncommercialservice.atlassian.net/browse/NDMP-1497)

NDMP-1497 - Update the API client for locked status
